# Etapa 1: Build
FROM node:18 AS build
WORKDIR /app

# Copiar arquivos de dependência
COPY package*.json ./
RUN npm install

# Copiar o restante do código
COPY . .

# Build da aplicação
RUN npm run build

# Etapa 2: Servir com Nginx
FROM nginx:alpine
# Copiar arquivos do build (Vite gera /dist)
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
