name: Deploy React App

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write   # necessário para atualizar o gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # --- Build React App ---
      - name: Install dependencies
        run: npm install
        working-directory: ./login-app

      - name: Build project
        run: npm run build
        working-directory: ./login-app

      # --- Deploy para GitHub Pages ---
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./login-app/dist

      # --- DockerHub: Login, Build e Push ---
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest -f ./login-app/Dockerfile ./login-app

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest
#teste